[Update] Write-up for the first phase.
robocomp/web pull request #236
Opened 2021-07-09 08:22 UTC by amarthyasasi

2021-07-11 18:59 UTC, pilarbachiller requested changes
Please, add links to your new posts in the file index.md

2021-07-13 05:57 UTC, amarthyasasi commented
Updated the links to new posts in index.md

2021-07-13 07:45 UTC, ibarbech commented
Please, remove .md extension of your link in the index.md

2021-07-13 07:48 UTC, amarthyasasi commented
Done.

2021-07-13 07:51 UTC, merged